import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen bg-gray-200">
        <div className="w-full bg-blue-200 text-center">RootLayout</div>
        {children}
      </body>
    </html>
  );
}
